### ISSUE TITLE
VPN: Document account creation flows across all platforms

### ISSUE THREAD

**Issue by malqinneh** [mozilla/dpx#17]
### Proposed project plan

**Goal**

- Optimize user signup flow based on user flows/journey maps across all platforms

![image.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/74471fe5-c3f6-43a3-b54a-04d009a882c9)
- Most users are currently dropping when they see the FxA flow (50%)

![image.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/fb3593a3-b64c-44f0-a6a5-49c05bf49487)

**Subtasks**

- [x] Map current FxA [sign in] and [sign up] flows on Website
![current-website.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/176dcd82-39be-4e45-834c-3e1e3071dfa8)
- [x] Map current FxA [sign in] and [sign up] flows on Mac OS
![current-macos.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/b3bcf121-1012-457f-8f05-d7d5a6df2de9)
- [x] Map current FxA [sign in] and [sign up] flows on Android
![current-android.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/480024b4-c751-4cd4-af65-266137daad9a)
- [x] Ideate solutions with the team on how might we optimize current FxA user journey

**Timeline and priority (if applicable)**

- Monday, October 5: Thomas/Gloria/Chris/Tyler/Mustafa to align on project scope and kick-off
- Wednesday, October 7: Map current FxA sign in and sign up flows across platforms
- Thursday, October 8: Have some suggestions for how might we optimize sign in/sign up flows

**Related issues**

- [VPN: Document payment flows across all platforms](https://app.zenhub.com/workspaces/dpx-experience-design-team-5f58057dfb3d02001259cefb/issues/mozilla/dpx-planning-and-intake/18)

**Relevant links**

- [VPN 1.5 PRD](https://docs.google.com/document/d/17YCN7jrcWupFAxzRrigMawM5cOpqFqALbPihs9qjgX8/edit?usp=sharing)
- [VPN 2.0 DPX investigations](https://docs.google.com/document/d/1Bpbgi2aw8ke-kqHvbA9Oqprig8uM8Rr61Q6dYh1YSEo/edit)
- [Figma Design](https://www.figma.com/file/ZSfD3ETagjCVQK8SQDc1VI/Sign-Up-Flow?node-id=0%3A1)
- [📝 VPN v2.1+ Improve Conversion Rate](https://docs.google.com/document/d/1EdECUyoWaUTIjPX0mI5u2e6VcwPj37rJD1Xnmc9EHr4/edit?usp=sharing)

**Comment by malqinneh** [comment]
@nshadowen314 do you know if we're legally required to collect [age] field during FxA creation flow?
![image.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/1f17ba7c-a2b9-47e5-8bbc-bdef89bc4906)

**Comment by malqinneh** [comment]
Capturing some comments from @isobelroe based on a sync today; 
- At a minimum; if we want to keep "30-day money back guarantee" it should be easier for users to request their money back
- Users are interested to see/use the app prior to subscribing

**Comment by malqinneh** [comment]
Shared [Loom video link](https://www.loom.com/share/4df24328bbc04262b9fb2e72d8c2bfe0) with team yesterday walking through a few potential iterations of FxA sign in/sign up (cc @isobelroe)

Will sync with Tyler Duzan and Chris More today to discuss further.

**Comment by malqinneh** [comment]
Three options presented yesterday (and today in VPN project meeting) to start a discussion:

![macos-option-1.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/e2a6cf96-79d0-4b82-a2d6-fd4b2dfba27b)

![macos-option-2.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/ec8500ac-0ffd-4f26-928d-30f1c98724ce)

![macos-option-3.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/86a10761-3d0f-41d2-b2aa-159f848b646d)

**Comment by nshadowen314** [comment]
Update - legal was not aware of the age gating on FxA and they are looking into it. Will update once I receive more information from them. Thanks @malqinneh !

**Comment by nshadowen314** [comment]
Update from Emily Litka and Alicia Gray (legal and trust/privacy) -

**Comment by malqinneh** [comment]
Update from team meeting October 8:

- Team consensus leans towards exploring full-fledged sign in solution separate from FxA
- Engineering a full-fledged sign in solution (separate from FxA) will take longer than 1.5 deadline
- Thomas and Mustafa to sync with Wennie about a 1.6 release
- Mustafa to iterate on option 3 and present to the team
- Mustafa to create prototypes to test with real users (in collaboration with Gloria)
