### ISSUE TITLE
VPN: Document payment flows across all platforms

### ISSUE THREAD

**Issue by malqinneh** [mozilla/dpx#18]
**Proposal**

**Goal**
Document existing payment flows for VPN across all supported platforms (iOS, Android, Mac OS/Linux/Windows/Browser) to understand existing challenges and opportunities for future payments (i.e. paypal) integration and improvements. 

**Subtasks**
- [x] Document existing payment flows for VPN across all supported platforms..
- [x] Document existing data.
- [x] Propose initial solutions for testing.

**Timeline**
Due Monday, October 19

**Comment by jwibowo** [comment]
Update: I was OOO last Wed-Friday. Picking up today and closing out next steps due last week.

**Comment by jwibowo** [comment]
Syncing with Mustafa tomorrow for handoff and sync.

**Comment by jwibowo** [comment]
**Figma source file (editable):** https://www.figma.com/file/ejDMYaKpm5bsYL5YvhItur/Mozilla-VPN?node-id=0%3A1

**Reference Links (so you don't have to re-dig them up):**
Apple Pay (subs): https://developer.apple.com/app-store/subscriptions/
Google Pay (subs): https://developer.android.com/google/play/billing/subsv
Google Pay (sub management): https://android-developers.googleblog.com/2020/06/new-features-to-acquire-and-retain-subscribers.html
Stripe Checkout: https://stripe.com/docs/billing/subscriptions/fixed-price
Stripe & Paypal: https://www.businessbloomer.com/use-paypal-stripe/ (just a short article from WooC about offering both).

**Comment by jwibowo** [comment]
![Screen Shot 2020-10-22 at 4.55.50 PM.png](https://images.zenhubusercontent.com/5f5924ee55cf57088e41149b/d76de1bf-72d8-41ad-8b3a-8d71a420f3d2)

**Comment by jwibowo** [comment]
![Screen Shot 2020-10-22 at 4.55.39 PM.png](https://images.zenhubusercontent.com/5f5924ee55cf57088e41149b/07c4a1b1-2510-45e9-a8f8-2a3d8efda329)

**Comment by jwibowo** [comment]
![Screen Shot 2020-10-22 at 4.55.11 PM.png](https://images.zenhubusercontent.com/5f5924ee55cf57088e41149b/c53a4420-0113-4f95-af23-6e1ad74ea444)

**Comment by jess-cook03** [comment]
@malqinneh Are you able to transfer this over into the mozilla-vpn-client repo? Just curious -- I'd love to keep the history here in how this issue/work as developed, but if I need to open an issue and just copy all this over thats fine too, just let me know! 
Thank you!

The same applies to issue #17
