### ISSUE TITLE
Pocket: New User Value Prototypes

### ISSUE THREAD

**Issue by DPX-designer** [mozilla/dpx#22]
Previous research has highlighted opportunities to better convey the value proposition Pocket offers to new users.

### Task
Design and deliver 4 high fidelity prototypes which provide methods for new Pocket website registrants to quickly discover and save content.

### Schedule
- [x] Onboarding Meeting with Pocket Team 
- [x] **Wed 21 Oct**: Present progress on prototype 1 to Pocket team
- [x] Design and deliver Prototype 1
- [x] Design and deliver Prototype 2
- [x] Design and deliver Prototype 3
- [x] Design and deliver Prototype 4 (implicit personalization)
- [ ] Design and deliver Prototype 5 (Add "+" prototype)
- [ ] Assist with usability test plans

**Comment by mcroud** [comment]
Prototype 1 (Article modules within My List) amended based on Pocket team feedback and delivered today.
Now working on Prototype 2 which includes the "Save for later" article prompt.

**Comment by mcroud** [comment]
Prototype 2 delivered. Positive feedback received so far, no amends as yet.
Beginning work on Prototype 3.

**Comment by mcroud** [comment]
Prototype 3 delivered.
Will now move onto the next prototype (personalisation experiment).

**Comment by mcroud** [comment]
Currently working on prototypes 4 and 5, awaiting feedback on options for proto 4 and clarification for proto 5

**Comment by mcroud** [comment]
Confirmed to expect a lot of feedback and answers for protos 4 and 5 by the time I start tomorrow.

**Comment by mcroud** [comment]
Prototype 4 "implicit personalization" completed and shared with Pocket team for feedback.
