### ISSUE TITLE
Pocket Community storyboarding initial ideas

### ISSUE THREAD

**Issue by lduggins855** [mozilla/dpx#23]
### Proposed project plan

**Goal**
Pocket + DPX recently kicked off Community work for q4! while we conduct 3 research studies, we would like to begin storyboarding initial ideas that came up to further our understanding and get feedback from users.

**Subtasks**

- [ ] kickoff with Laurie, Alex, and Daria to get further info on request

- [ ] storyboard for small groups (teams, friends, classes)
- closed groups to share and discuss content. Venmo, dropbox, google drive, box, wetransfer, wecollect, are.nainvision, miro, pinterest

- [ ] storyboard for public curation and sharing
- seeing recs from your network. examples: newsletters, Nuzzel, publishers, medium, pinterest, spotify 
-  How can we surface the inputs of why someone sees a recommendation that makes them feel empowered and part of a community and that increases their trust in the legitimacy of that content? (How do we increase trust in content via community features?)

- [ ] storyboard for social
- connecting people to the value of the good web
-a feeling that there are others participating at the same time or have similar interests or that one belongs to a tribe that revolves around shared value/interests/skills (e.g. book clubs; nutrition self-care like Weight Watchers or other communities related to food and dieting; spiritual, emotional or mental health care boards or clubs like The Mighty, etc.) vs having a social presence by commenting, liking, etc 

- [ ] storyboard for a call to action
- scaffold/enable people to be proactive and TAKE ACTION as a community, using content as an anchor (e.g. volunteering apps, group-buying discount services, meetup, political groups, kickstarter, nextdoor, care2
- Ask people if they’d like to take action on something. connect those dots and provide tools for taking action. 

**Timeline and priority**

- [ ] 2 weeks.  storyboards=low fidelity

**Additional context**
vendor research doc:
https://docs.google.com/document/d/1JnUQa-j8KyyDyA67-malKYkzhwfn_NIWyVDulU2j6Rs/edit#

kickoff doc:
https://docs.google.com/document/d/1a20REafhRUHNdTIXoyA7_IDx1oMNtbrg8gmRG5VmM64/edit
slack: pocket-community-ideation

quant survey doc:
https://docs.google.com/document/d/1R6W7XKRskt7wxb0KFp1ZRJERX5kkBYjAZSxZK3J1Wwg/edit#

**Comment by lduggins855** [comment]
@malqinneh hello! We're hoping to get some storyboard concepts to help visualize the above ideas for pocket community.  Do you think there is bandwidth for this project in the coming weeks? ty!

**Comment by malqinneh** [comment]
@lduggins855 thanks for flagging! I added the tags so that this issue shows up in our ZenHub board (when it's filtered).

I will post an update in this issue tomorrow after I sync with Dan later today and let you know!

**Comment by malqinneh** [comment]
@lduggins855 update on this; XD is at capacity this week but will be able to pick this up next week if that works. Let me know!

**Comment by lduggins855** [comment]
yes, thank you!!
