### ISSUE TITLE
Prospector Concept Storyboards

### ISSUE THREAD

**Issue by malqinneh** [mozilla/dpx#27]
### Proposed project plan

**Goal**
Storyboard 4-6 concepts for FoxBox to run unmoderated & moderated tests. Concepts will come from this [list](https://docs.google.com/spreadsheets/d/1nidKdaIW3pTIBO_UTpWxBHB4BHd3jcJRZse3aCJdf2A/edit?usp=sharing) and will look similar to [this](https://drive.google.com/file/d/13H2hSvrkXDk5ONt02f-Uhuas2njZhpua/view?usp=sharing).

Specs: .jpeg files, image size (minimum): width: 600px; height: 600px.

**Subtasks**
List all action items or subtasks to accomplish the above goal.

- [x]  Sync with Heather and identify and align on deliverables. 2/4-6 concepts approved for testing.

- [x] Sketch out first iteration

- [x] Research references/assets. 1/4-6

- [x] First iteration of concept storyboards for Foxbox/Privacy vault.

- [x] Sync with Heather for critique of storyboards.  1/4-6

- [x] Receive feedback on Foxbox/Privacy vault concept storyboards.

- [x] Add text to revised version.

**Timeline and priority**
Rough timeline based on a 5-day sprint.

- [x] Wednesday, 11/11/20. First iteration of Foxbox/Privacy vault concept. *awaiting feedback*

- [x] Thursday, 11/12/2020 First iteration of Account manager concept. *awaiting approval*

- [x] Wednesday, 11/18/2020 Delivery of images for 4 concepts.

**Linked issues (if applicable)**
Please list any other GitHub issues that are constrained by or dependent on this feature here.

- [Title](link)

**Additional context**
Add any resources, documents, or relevant links for context here.
