### ISSUE TITLE
UX test structure for Microsoft Teams

### ISSUE THREAD

**Issue by fernzharp** [mozilla/dpx#88]
### Proposed project plan

**Goal**
Create a UX test structure for Microsoft Teams as part of our research for DPX. It could help us better understand the needs that aren't being met with Teams (especially for educators).

**Subtasks**

- [x] Brainstorm possible test structure

- [x] [Put proposed structure into a sharable document](https://docs.google.com/document/d/1TL-DDNxuh45YK0xi77sWvbu_sGXT32cn-7eRKY44nPA/edit?usp=sharing)

- [ ] Sync with Heather and Matt and align on deliverables

**Additional context**
Add any resources, documents, or relevant links for context here.

- [Title](link)

**Comment by fernzharp** [comment]
Test concept 1 here: [https://docs.google.com/document/d/1TL-DDNxuh45YK0xi77sWvbu_sGXT32cn-7eRKY44nPA/edit?usp=sharing](https://docs.google.com/document/d/1TL-DDNxuh45YK0xi77sWvbu_sGXT32cn-7eRKY44nPA/edit?usp=sharing)
Next step is to sync with Matt and Heather on proposed test and revise as needed.
